### ISSUE TITLE
Support whitespace in nuget package path

### ISSUE THREAD

**Issue by Golle** [MichalStrehovsky/PublishAotCompressed#3]
MSBuild will fail when the nuget packages are cached in a path that contains whitespaces. This can be fixed by adding `&quot;` to the exec statement.

Replace this line https://github.com/MichalStrehovsky/PublishAotCompressed/blob/b3122510f61da0f238ad8fc54e152e310e878dde/src/PublishAotCompressed.targets#L22

with 
```
<Exec Command="&quot;$(MSBuildThisFileDirectory)../tools/$(_OSIdentifier)-$(_OSHostArch)/upx&quot; $(_UpxArgs) $(NativeBinary)" />
```

**Comment by MichalStrehovsky** [comment]
Thanks! Kicked off a [new build](https://github.com/MichalStrehovsky/PublishAotCompressed/actions/runs/3179482624) and uploaded to nuget. 0.0.4 will have the fix.
