### ISSUE TITLE
linux-arm64 support

### ISSUE THREAD

**Issue by KeterSCP** [MichalStrehovsky/PublishAotCompressed#5]
Hi,

I see there is only support for x86_64 for both Windows and Linux. Would it be possible to add linux-arm64?

When I tried to manually download binary for arm64 from https://github.com/upx/upx/releases/tag/v3.96 and placed it into
`.nuget/packages/publishaotcompressed/0.0.3/tools`, publish of "Hello world" app was successful, but after running, I got
segfault

**Comment by MichalStrehovsky** [comment]
Do you get a segfault also if you publish without compression and then run `upx --best thenameofyourbinary`?

That would indicate it's an issue with UPX.

I didn't add ARM64 because I didn't have a convenient way to test it.

**Comment by KeterSCP** [comment]
Yeah, manually running UPX on published binary also produces a segfault in runtime. Closing then as it's not related to this repo

**Comment by KeterSCP** [comment]
BTW, found an issue that might be related https://github.com/upx/upx/issues/611
